### ISSUE TITLE
I get a 404 on this link

### ISSUE THREAD

**Issue by mattvenn** [analogicus/jnw_spice_sky130A#1]
https://github.com/analogicus/jnw_spice_sky130A/blob/ee4f890e834d4ee6b74dd330ee854fa8cef8103b/README.md?plain=1#L20

**Comment by wulffern** [comment]
Indeed, it's only available here https://analogicus.github.io/jnw_spice_sky130A/ 

It does not exist in the git repository. It's generated during the github action

**Comment by wulffern** [comment]
@mattvenn you could argue I should use a different file than the readme for the index html, but then I'd be duplicating info. Need to think about it.

**Comment by wulffern** [comment]
Added a comment to the readme.

**Comment by wulffern** [comment]
and thanks for the issue @mattvenn , much appreciated.

**Comment by mattvenn** [comment]
I just came straight from the video and clicked your repo. 
We have basically the same issue with TT repos - should they 'work' but with my demo, or be 'broken' because you have to add your demo.

**Comment by wulffern** [comment]
Removed the "What" section from the readme, it's now added during the action to avoid confusion.
